server:
  port: 7001

# 单机版
#eureka:
#  instance:
#    hostname: localhost #eureka服务端的实例名称
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # false 表示不需要去获取注册的服务
#    fetch-registry: false
#    service-url:
#      # 设置与Eureka Server 交互的地址,查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 集群版
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示不需要去获取注册的服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server 交互的地址,查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/